version: '3.4'

services:

  mongodb:
    image: mongo:latest

  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: UserManagement.API/Dockerfile
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
