@protocol=https
@hostname=localhost
@port=7159
@version=v1
@endpoint=api/{{version}}/users

@url={{protocol}}://{{hostname}}:{{port}}/{{endpoint}}


### Attemp to create new user -- invalid request
POST {{url}}
Content-Type: application/json

{
  "name": "string",
  "username": "string",
  "email": "test@string.com",
  "address": {
    "street": "string",
    "suite": "string",
    "city": "string",
    "zipcode": "string",
    "geo": {
      "lat": "0",
      "lng": "0"
    }
  },
  "phone": "string",
  "website": "www.string.com",
  "company": {
    "name": "string",
    "catchPhrase": "string",
    "bs": "string"
  }
}


### Get all users by email contains @. Get page 1 and pageSize 2
GET {{url}}?email=%40&page=1&pageSize=2
Accept: application/json


### Get UserById 1
GET {{url}}/1
Accept: application/json


### Get UserById 2
GET {{url}}/2
Accept: application/json


### Delete user by id 1
DELETE {{url}}/1


### Delete non existing user by id 0 -- invalid request
DELETE {{url}}/0
